export const COUNTRIES = [
  { code: "US", name: "United States", flag: "🇺🇸" },
  { code: "GB", name: "United Kingdom", flag: "🇬🇧" },
  { code: "DE", name: "Germany", flag: "🇩🇪" },
  { code: "CA", name: "Canada", flag: "🇨🇦" },
  { code: "AU", name: "Australia", flag: "🇦🇺" },
  { code: "FR", name: "France", flag: "🇫🇷" },
  { code: "JP", name: "Japan", flag: "🇯🇵" },
  { code: "BR", name: "Brazil", flag: "🇧🇷" },
  { code: "NL", name: "Netherlands", flag: "🇳🇱" },
  { code: "AE", name: "United Arab Emirates", flag: "🇦🇪" },
];

export const NICHES = [
  { id: "beauty", name: "Beauty & Skincare", icon: "✨", trend: "hot" },
  { id: "fitness", name: "Fitness & Health", icon: "💪", trend: "rising" },
  { id: "tech", name: "Tech Gadgets", icon: "🔌", trend: "hot" },
  { id: "home", name: "Home & Living", icon: "🏠", trend: "stable" },
  { id: "fashion", name: "Fashion & Accessories", icon: "👗", trend: "rising" },
  { id: "pets", name: "Pet Supplies", icon: "🐾", trend: "hot" },
];

export const CHAMPION_PRODUCTS = [
  {
    id: "1",
    name: "LED Therapy Mask Pro",
    image: "https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=400",
    niche: "beauty",
    profitMargin: "62%",
    orders: "1.2K-2.5K",
    source: "TikTok",
    trendLevel: "hot",
    price: 29.99,
    sellPrice: 79.99,
    description: "Professional LED light therapy mask with 7 color modes for skin rejuvenation.",
    benefits: ["Reduces wrinkles and fine lines", "Improves skin elasticity", "Kills acne-causing bacteria", "Non-invasive treatment"],
    targetAudience: "Women 25-45, skincare enthusiasts, beauty influencer followers",
  },
  {
    id: "2",
    name: "Smart Posture Corrector",
    image: "https://images.unsplash.com/photo-1576091160550-2173dba999ef?w=400",
    niche: "fitness",
    profitMargin: "71%",
    orders: "800-1.8K",
    source: "Facebook",
    trendLevel: "rising",
    price: 12.99,
    sellPrice: 44.99,
    description: "Intelligent posture corrector with vibration reminder and app connectivity.",
    benefits: ["Real-time posture monitoring", "Gentle vibration reminders", "App tracking progress", "Comfortable for all-day wear"],
    targetAudience: "Office workers 22-50, remote workers, health-conscious individuals",
  },
  {
    id: "3",
    name: "Wireless Charging Pad 3-in-1",
    image: "https://images.unsplash.com/photo-1586953208448-b95a79798f07?w=400",
    niche: "tech",
    profitMargin: "58%",
    orders: "2K-4K",
    source: "TikTok",
    trendLevel: "hot",
    price: 15.99,
    sellPrice: 39.99,
    description: "Sleek 3-in-1 wireless charging station for phone, watch, and earbuds.",
    benefits: ["Charges 3 devices simultaneously", "Fast charging technology", "Compact elegant design", "Universal compatibility"],
    targetAudience: "Tech enthusiasts 18-40, Apple/Samsung users, gadget lovers",
  },
  {
    id: "4",
    name: "Automatic Pet Feeder WiFi",
    image: "https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=400",
    niche: "pets",
    profitMargin: "55%",
    orders: "600-1.2K",
    source: "Facebook",
    trendLevel: "rising",
    price: 24.99,
    sellPrice: 59.99,
    description: "WiFi-enabled automatic pet feeder with app control and camera.",
    benefits: ["Schedule meals remotely", "Built-in camera", "Voice recording feature", "Portion control"],
    targetAudience: "Pet owners 25-55, busy professionals, tech-savvy pet lovers",
  },
  {
    id: "5",
    name: "Aesthetic Cloud Lamp",
    image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400",
    niche: "home",
    profitMargin: "68%",
    orders: "1.5K-3K",
    source: "TikTok",
    trendLevel: "hot",
    price: 8.99,
    sellPrice: 34.99,
    description: "Floating cloud lamp with thunder effect and remote control.",
    benefits: ["Stunning visual effect", "Multiple lighting modes", "Remote controlled", "Perfect for content creators"],
    targetAudience: "Gen Z 16-28, home decor enthusiasts, TikTok creators",
  },
  {
    id: "6",
    name: "Portable Neck Massager",
    image: "https://images.unsplash.com/photo-1544161515-4ab6ce6db874?w=400",
    niche: "fitness",
    profitMargin: "65%",
    orders: "900-2K",
    source: "Facebook",
    trendLevel: "stable",
    price: 18.99,
    sellPrice: 54.99,
    description: "EMS neck massager with heat therapy and multiple intensity levels.",
    benefits: ["Relieves neck pain instantly", "Heat therapy included", "Portable and lightweight", "USB rechargeable"],
    targetAudience: "Adults 30-60, office workers, people with chronic neck pain",
  },
];

export const TRENDING_ADS = [
  { id: "1", product: "LED Therapy Mask", views: "2.4M", likes: "180K", comments: "12K", duration: "0:32", platform: "TikTok" },
  { id: "2", product: "Posture Corrector", views: "1.8M", likes: "95K", comments: "8K", duration: "0:45", platform: "Facebook" },
  { id: "3", product: "Wireless Charger", views: "3.1M", likes: "220K", comments: "15K", duration: "0:28", platform: "TikTok" },
  { id: "4", product: "Pet Feeder", views: "900K", likes: "65K", comments: "5K", duration: "1:02", platform: "Instagram" },
  { id: "5", product: "Cloud Lamp", views: "5.2M", likes: "410K", comments: "28K", duration: "0:18", platform: "TikTok" },
  { id: "6", product: "Neck Massager", views: "1.5M", likes: "88K", comments: "7K", duration: "0:55", platform: "Facebook" },
];

export const BANNERS = Array.from({ length: 60 }, (_, i) => ({
  id: `banner-${i + 1}`,
  name: `Banner Design ${i + 1}`,
  category: ["minimalist", "bold", "elegant", "tech", "lifestyle", "premium"][i % 6],
  colors: [
    ["#7B2CFF", "#00C2FF"],
    ["#FF6B35", "#FFD700"],
    ["#00C2FF", "#00FF88"],
    ["#FF3366", "#7B2CFF"],
    ["#1A1A2E", "#E94560"],
    ["#667EEA", "#764BA2"],
  ][i % 6],
}));

export const generateTrendData = () =>
  Array.from({ length: 30 }, (_, i) => ({
    day: `Day ${i + 1}`,
    orders: Math.floor(Math.random() * 500) + 100,
    engagement: Math.floor(Math.random() * 10000) + 2000,
  }));

export const generateAIProductPage = (product: typeof CHAMPION_PRODUCTS[0]) => ({
  title: `${product.name} — ${product.benefits[0]}`,
  headline: `Transform Your Life with the ${product.name}`,
  description: product.description,
  benefits: product.benefits,
  objections: [
    { q: "Is it worth the price?", a: `Absolutely. The ${product.name} pays for itself with long-term benefits and premium quality.` },
    { q: "How long does shipping take?", a: "We offer fast shipping within 7-14 business days worldwide with full tracking." },
    { q: "What if I don't like it?", a: "We offer a 30-day money-back guarantee. No questions asked." },
  ],
  faq: [
    { q: "How do I use it?", a: "Simply follow the included quick-start guide. Most customers set up in under 5 minutes." },
    { q: "Is there a warranty?", a: "Yes, all products come with a 1-year manufacturer warranty." },
    { q: "Can I track my order?", a: "Yes, you'll receive tracking information within 24 hours of purchase." },
  ],
  cta: `Get Your ${product.name} Now — Limited Stock!`,
  urgency: "⚡ Only 47 units left at this price",
});
